[providers]
providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"

[build]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/refs/tags/23.05.tar.gz"

[phases.setup]
nixPkgs = ["python39", "gcc", "libGL", "glib", "glibc", "libGLU", "pkg-config"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "chmod +x /app/boot.sh",
    "echo 'Menghubungkan dependensi OpenCV...'",
    "GL=$(find /nix/store -name 'libGL.so.1' | head -n 1) && ln -sf $GL /usr/lib/libGL.so.1 || echo 'Hubungan libGL gagal'",
    "GLIB=$(find /nix/store -name 'libglib-2.0.so.0' | head -n 1) && ln -sf $GLIB /usr/lib/libglib-2.0.so.0 || echo 'Hubungan glib gagal'",
    "GTHREAD=$(find /nix/store -name 'libgthread-2.0.so.0' | head -n 1) && ln -sf $GTHREAD /usr/lib/libgthread-2.0.so.0 || echo 'Hubungan gthread gagal'",
    "ldd /opt/venv/lib/python3.9/site-packages/cv2/*.so || echo 'Pemeriksaan ldd gagal'"
]

[start]
cmd = "./boot.sh"