providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"

[build]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/refs/tags/23.05.tar.gz"

[phases.setup]
nixPkgs = ["python39", "mesa", "libGL", "libGLU", "glib", "glibc", "pkg-config"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo '✅ Build selesai.'"
]

[start]
cmd = "bash boot.sh"
