providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"

[build]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/refs/tags/23.05.tar.gz"

[phases.setup]
nixPkgs = ["python39", "gcc", "libGL", "glib", "glibc", "libGLU", "pkg-config"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "chmod +x /app/boot.sh",
  "echo 'Menghubungkan dependensi OpenCV...'",
  "GL=$(find /nix/store -name 'libGL.so.1' | head -n 1) && ln -sf $GL /opt/venv/lib/libGL.so.1 || echo 'Link libGL gagal'",
  "GLIB=$(find /nix/store -name 'libglib-2.0.so.0' | head -n 1) && ln -sf $GLIB /opt/venv/lib/libglib-2.0.so.0 || echo 'Link glib gagal'",
  "GTHREAD=$(find /nix/store -name 'libgthread-2.0.so.0' | head -n 1) && ln -sf $GTHREAD /opt/venv/lib/libgthread-2.0.so.0 || echo 'Link gthread gagal'"
]

[start]
cmd = "bash boot.sh"

